version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=dm_user
      - MYSQL_PASSWORD=dm_pass
      - MYSQL_DATABASE=dm_db

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf 

  mysql:
    image: mysql:latest
    container_name: mysql_container
    command:
        - '--skip-log-bin'
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: dm_db
      MYSQL_USER: dm_user
      MYSQL_PASSWORD: dm_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./conf.cnf:/etc/mysql/conf.d/custom_mysql.cnf
      - ./logs:/var/log/mysql

volumes:
  mysql_data:
