version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=dm_user
      - MYSQL_PASSWORD=dm_pass

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: dm_db
      MYSQL_USER: dm_user
      MYSQL_PASSWORD: dm_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  mysql_data:
