CREATE DATABASE IF NOT EXISTS dm_db;
CREATE DATABASE IF NOT EXISTS dm_test_db;
CREATE USER IF NOT EXISTS 'dm_user' IDENTIFIED BY 'dm_pass';

GRANT ALL PRIVILEGES ON dm_db.* TO 'dm_user';
GRANT ALL PRIVILEGES ON dm_test_db.* TO 'dm_user';

USE dm_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    activation_status TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE dm_test_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    activation_status TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
